apiVersion: v1
kind: ReplicationController
metadata:
  name: gcp-workshop-sandbox-v3
spec:
  replicas: 3
  selector:
    App: gcp-workshop-sandbox
  template:
    metadata:
      labels:
        App: gcp-workshop-sandbox
    spec:
      containers:
          - name: gcp-workshop-sandbox
            image: tomqwu/gcp-workshop:0.0.2
            ports:
              - containerPort: 3000
            env:
              - name: GITSHA
                value: git9232427
