apiVersion: v1
kind: ReplicationController
metadata:
  name: gcp-workshop-sandbox-v2
spec:
  replicas: 3
  selector:
    app: gcp-workshop-sandbox
    deployment: v2
  template:
    metadata:
      labels:
        app: gcp-workshop-sandbox
        deployment: v2
    spec:
      containers:
      - name: gcp-workshop-sandbox
        image: tomqwu/gcp-workshop:0.0.2
        ports:
        - containerPort: 3000
        env:
        - name: GITSHA
          value: "9232427"
